### ISSUE TITLE
Problem with forcing Makefile to python2

### ISSUE THREAD

**Issue by sveetch** [emencia/Epaster#5]
Last change to force python2 usage only in Makefile install action cause troubles on some distribution (debian reported, also OSX reported too) :

`virtualenv --no-site-packages --setuptools --python python2 .`

We can't force a hardcoded absolute path to python2 binaries because it can change on some system.

The following is said as valid for all systems :

    PYTHON_PATH=`which python2`
    virtualenv --no-site-packages --setuptools --python=$PYTHON_PATH .

This need to be tested on the many supported system (not Window) before introducing as a patch.

**Comment by sveetch** [comment]
So the test should be a simple shellscript to test the returned version from the python binary defined from PYTHON_PATH, give it to users on various systems and validate the returned version to be Python2 (if it did not fail).

**Comment by slothyrulez** [comment]
On osx 10.10, there are:
- /usr/bin/python
- /usr/bin/python2.6
- /usr/bin/python2.7

```
PYTHON_PATH=`which python2.7`
if [ -e "$PYTHON_PATH" ]; then
  virtualenv --no-site-packages --setuptools --python=$PYTHON_PATH .
else
  virtualenv --no-site-packages --setuptools  .
```

Or maybe wget ...> make > make install...

**Comment by cecedille1** [comment]
% PYTHON_PATH=`which python2`
    % virtualenv --no-site-packages --setuptools --python=$PYTHON_PATH /tmp/xxxxm
    Running virtualenv with interpreter /usr/bin/python2
    New python executable in /tmp/xxxxm/bin/python2
    Also creating executable in /tmp/xxxxm/bin/python
    Installing setuptools, pip...done.*

Works for ArchLinux, it also works with python2.7, but not python2.6

**Comment by jdavid** [comment]
So Mac is like Linux, so we just use ``--python /usr/bin/python2.7`` hard coded.

We don't support 2.6 anyway.

**Comment by sveetch** [comment]
Ok, the hint from @slothyrulez looks very nice, i tested on multiple machine, even osx and it work nice.

Just have to find how to make a conditionnal rule in Makefile with this and it will go.

**Comment by sveetch** [comment]
Ok it's done since version 2.2.9 (commit 265c5775ae), has been done also on emencia_paste_djangocms_3==1.3.7

**Comment by sveetch** [comment]
Obviously this does not work on OSX... We probably have to force on python2.7.. or resolve this using a distinct shell script because we can do it in Makefile

**Comment by sveetch** [comment]
Done since version 2.3.1 (commit 477beb7db3) and emencia_paste_djangocms_3==1.4.0
